spring:
  application:
    name: multiple-LLM
  ai:
    chat:
      client:
        enabled: false
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-4o
    anthropic:
      api-key: ${ANTHROPIC_KEY}
      chat:
        options:
          model: claude-3-5-sonnet-20240620